### ISSUE TITLE
Exception opening .ome.tiff

### ISSUE THREAD

**Issue by ctrueden** [scifio/scifio-ome-xml#25]
From [a thread on the ImageJ forum](http://forum.imagej.net/t/1847):

> A fresh installation of the latest Fiji with SCIFIO enabled fails to read [this .ome.tiff image](https://powerfolder.dkfz.de/dl/fiDWsj62i3YmZpcvrs54B1Ns/fiji_scifio_exception.zip). The Bioformats Importer reads successfully. Is this the right place to report this?
> ```
Warning:  org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser: Property 'http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit' is not recognized.
Warning:  org.apache.xerces.parsers.SAXParser: Feature 'http://javax.xml.XMLConstants/feature/secure-processing' is not recognized.
Warning:  org.apache.xerces.parsers.SAXParser: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.
Warning:  org.apache.xerces.parsers.SAXParser: Property 'http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit' is not recognized.
Warning:  org.apache.xerces.parsers.SAXParser: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.
Warning:  org.apache.xerces.parsers.SAXParser: Property 'http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit' is not recognized.
[WARNING] Image ID 'D:\Lorenz\2016 06 06 stainings\3 - bleach_new_switch track every z-stack__AQ__W0001__P0001__T0004.czi': missing plane #0.  Using TiffReader to determine the number of planes.
[INFO] Reading IFDs
[INFO] Populating metadata
[INFO] Checking comment style
[INFO] Reading IFDs
[INFO] Populating metadata
[INFO] Checking comment style
Exception in thread "DrawAndDrop" java.lang.ArrayIndexOutOfBoundsException: 1
	at io.scif.ome.formats.OMETIFFFormat$Reader.openPlane(OMETIFFFormat.java:1116)
	at io.scif.ome.formats.OMETIFFFormat$Reader.openPlane(OMETIFFFormat.java:1082)
	at io.scif.AbstractReader.openPlane(AbstractReader.java:167)
	at io.scif.filters.ChannelFiller.openPlane(ChannelFiller.java:171)
	at io.scif.filters.ChannelFiller.openPlane(ChannelFiller.java:151)
	at io.scif.filters.PlaneSeparator.openPlane(PlaneSeparator.java:305)
	at io.scif.filters.AbstractReaderFilter.openPlane(AbstractReaderFilter.java:244)
	at io.scif.img.ImgOpener.read(ImgOpener.java:836)
	at io.scif.img.ImgOpener.read(ImgOpener.java:818)
	at io.scif.img.ImgOpener.read(ImgOpener.java:818)
	at io.scif.img.ImgOpener.read(ImgOpener.java:818)
	at io.scif.img.ImgOpener.read(ImgOpener.java:798)
	at io.scif.img.ImgOpener.readPlanes(ImgOpener.java:785)
	at io.scif.img.ImgOpener.openImgs(ImgOpener.java:383)
	at io.scif.img.ImgOpener.openImgs(ImgOpener.java:269)
	at io.scif.img.ImgOpener.openImgs(ImgOpener.java:146)
	at io.scif.services.DefaultDatasetIOService.open(DefaultDatasetIOService.java:124)
	at io.scif.services.DefaultDatasetIOService.open(DefaultDatasetIOService.java:109)
	at io.scif.io.DatasetIOPlugin.open(DatasetIOPlugin.java:75)
	at io.scif.io.DatasetIOPlugin.open(DatasetIOPlugin.java:50)
	at net.imagej.legacy.plugin.DefaultLegacyOpener.open(DefaultLegacyOpener.java:135)
	at net.imagej.legacy.DefaultLegacyHooks.interceptDragAndDropFile(DefaultLegacyHooks.java:363)
	at ij.plugin.DragAndDrop.openFile(DragAndDrop.java)
	at ij.plugin.DragAndDrop.run(DragAndDrop.java:159)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jaywarrick** [comment]
I believe I have a similar issue. All ome.tifs exported from the IDEAS software (http://www.emdmillipore.com/US/en/life-science-research/cell-analysis/amnis-imaging-flow-cytometers/analysis-acquisition-software/B6ib.qB.iY8AAAFLCn4p.zHg,nav) seem to open in standard FIJI but not FIJI with scifio enabled.

Error below [in DEBUG mode]

[error.txt](https://github.com/scifio/scifio-ome-xml/files/884722/error.txt)

**Comment by jaywarrick** [comment]
Here is the image file associated with the error mentioned in the previous comment.

https://drive.google.com/file/d/0BzopfqjGpdu8a2I0N0hkdHgtTEE/view?usp=sharing
